const InmuebleArray = [
    {
        id: 1001,
        tipo: "casa",
        direccion: "Av Prolongación Javier Prado",
        precio: "150000",
        titulo: "Amplia casa en Ate",
        habitaciones: "4",
        baños: "5",
        area: "280m²",
        descripcion: "Lorem ipsum dolor sit amet",
        mascotas: "no",
        piso: "1",
        distrito: "Ate",
        telefono: "1456165161",
        imagenDestacada: "1001-1.jpg"
    },
    {
        id: 1002,
        tipo: "departamento",
        direccion: "Av Carlos izaguirre",
        precio: "25000",
        titulo: "Departamento de lujo",
        habitaciones: "3",
        baños: "2",
        area: "125m²",
        descripcion: "Lorem ipsum dolor sit amet",
        mascotas: "si",
        piso: "7",
        distrito: "Los Olivos",
        telefono: "925877884",
        imagenDestacada: "1002-1.jpg"
    },
    {
        id: 1003,
        tipo: "departamento",
        direccion: "Av Las Palmeras",
        precio: "125000",
        titulo: "Departamento duplex",
        habitaciones: "3",
        baños: "2",
        area: "125m²",
        descripcion: "Lorem ipsum dolor sit amet",
        mascotas: "si",
        piso: "7",
        distrito: "Los Olivos",
        telefono: "925877884",
        imagenDestacada: "1003-1.jpg"
    },
    {
        id: 1004,
        tipo: "departamento",
        direccion: "Av Universitaria",
        precio: "95000",
        titulo: "Depa a estrenar",
        habitaciones: "3",
        baños: "2",
        area: "125m²",
        descripcion: "Lorem ipsum dolor sit amet",
        mascotas: "si",
        piso: "7",
        distrito: "Los Olivos",
        telefono: "925877884",
        imagenDestacada: "1004-1.jpg"
    },
    {
        id: 1005,
        tipo: "departamento",
        direccion: "Av Elmer Faucett",
        precio: "115000",
        titulo: "Mini-departamento en El Callao",
        habitaciones: "3",
        baños: "2",
        area: "125m²",
        descripcion: "Lorem ipsum dolor sit amet",
        mascotas: "si",
        piso: "7",
        distrito: "Los Olivos",
        telefono: "925877884",
        imagenDestacada: "1005-1.jpg"
    },
    {
        id: 1006,
        tipo: "departamento",
        direccion: "Av Ricardo Palma",
        precio: "180000",
        titulo: "Departamento con terraza",
        habitaciones: "2",
        baños: "1",
        area: "105m²",
        descripcion: "Lorem ipsum dolor sit amet",
        mascotas: "si",
        piso: "7",
        distrito: "Los Olivos",
        telefono: "925877884",
        imagenDestacada: "1006-1.jpg"
    }

]
